blank_issues_enabled: false

contact_links:
  - name: ENIGMA community channels
    url: https://discord.com/invite/Kz67atZ
    about: Please ask for technical support on one of the other community channels, not here.
