# This file is to deploy to Github pages.
# This file is written from https://www.sphinx-doc.org/en/master/tutorial/deploying.html.

name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: .
        build-command: make html

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: _build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        publish_branch: master-published
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
